### PR TITLE
fixed <ul> cannot appear as a descendant of <p> error

### LINKED ISSUE #335: Policies page invalid tag nesting
Simple fix, but there's a rogue `<ul>` tag within a `<p>` tag in the policies page:
image

### PR DESCRIPTION
**Pull request by ericyche**
Screen Shot 2022-11-05 at 9 27 25 PM
No more errors about `ul` being descendent of `p`! 

closes #335

### CODE REVIEW

File: csm_web/frontend/src/components/Policies.tsx [hunk 1]
```diff
@@ -177,22 +177,22 @@ export default class Policies extends React.Component {
...
-            <p>
+            <span>
               {faq.body.p8}
               <ul>
                 <li> {faq.body.li1} </li>
                 <li> {faq.body.li2} </li>
               </ul>
-            </p>
-            <p>
+            </span>
```
Comment (smartspot2) [inline csm_web/frontend/src/components/Policies.tsx:186]: Is there any particular reason why the body text needs to be grouped with the list text like this? I feel an easier solution is to just move the closing tag before the `<ul>` tags.

**Comment by smartspot2** [comment]
Additionally, while you're at it, there is a leftover console log as well at the top of the file.

File: csm_web/frontend/src/components/Policies.tsx (hunk 1 above)
Comment (ericyche) [reply csm_web/frontend/src/components/Policies.tsx]: oo u are very right! updated

**Review by smartspot2 — APPROVED** [review]
Looks good; rebase and squash these commits, and we can merge it.

File: csm_web/frontend/src/components/Policies.tsx [hunk 2]
```diff
@@ -11,7 +11,6 @@ export default class Policies extends React.Component {
     const aff = SECTIONS.affinitySections;
     const forUnit = SECTIONS.csmForUnit;
     const faq = SECTIONS.faq;
-    console.log(SECTIONS);
```
Comment (noortor) [inline csm_web/frontend/src/components/Policies.tsx:14]: squash

**Review by noortor — CHANGES_REQUESTED** [review]

File: csm_web/frontend/src/components/Policies.tsx (hunk 2 above)
Comment (smartspot2) [reply csm_web/frontend/src/components/Policies.tsx:14]: get squashed, kid

**Review by noortor — APPROVED** [review]
